name: Release Controller

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACR_REGISTRY_NAME: containerbutler # example: "myRegistry" .azurecr.io
  ACR_REPO_NAME: ${{ github.event.repository.name }} # example: myRepo
  KEY_ID: ${{ secrets.ACR_KEY_ID }} # example: https://mynotationakv.vault.azure.net/keys/notationLeafCert/c585b8ad8fc542b28e41e555d9b3a1fd
  NOTATION_EXPERIMENTAL: 1 # [Optional] when set, use Referrers API in the workflow (Recommended)

jobs:
  goreleaser:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    name: GoReleaser build, push to GHCR/DockerHub/ACR, & sign with cosign/notation
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.26.2
          check-latest: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: arm64,s390x
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Log in to Azure with your service principal 
      - name: Azure login
        uses: Azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Construct & store ACR login server
        run: |
          ACR_LOGIN_SERVER=$(az acr show \
            --name ${{ env.ACR_REGISTRY_NAME }} \
            --query loginServer \
            -o tsv)
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
      # Log in to your ACR registry
      - name: Login to Azure Container Registry (Docker)
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 #v4.1.1
      - name: Check install!
        run: cosign version
      # Install Notation CLI with the default version "1.0.0"
      - name: setup notation
        uses: notaryproject/notation-action/setup@b6fee73110795d6793253c673bd723f12bcf9bbb # v1.2.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get GoReleaser digest and sign GHCR & DockerHub images
        run: |
          echo "==== dist/digests.txt ===="
          cat dist/digests.txt
          DIGEST_RAW=$(grep "ghcr.io" dist/digests.txt | head -n1 | awk '{print $1}')
          if [ -z "$DIGEST_RAW" ]; then
            echo "ERROR: Digest not found!"
            exit 1
          fi
          DIGEST="sha256:${DIGEST_RAW}"
          GHCR_IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          DOCKERHUB_IMAGE="docker.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          echo "Using digest: $DIGEST"
          echo "target_artifact_reference=${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPO_NAME }}@$DIGEST" >> $GITHUB_ENV
          echo "Signing GHCR image: ${GHCR_IMAGE}@${DIGEST}"
          cosign sign --yes ${GHCR_IMAGE}@${DIGEST}
          echo "Signing DockerHub image: ${DOCKERHUB_IMAGE}@${DIGEST}"
          cosign sign --yes ${DOCKERHUB_IMAGE}@${DIGEST}
      - name: Get runner public IP
        id: ip
        run: echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT
      - name: Allow runner IP in Key Vault
        run: |
          az keyvault network-rule add \
            --name computerbutler-keyvault \
            --resource-group computerbutler \
            --ip-address ${{ steps.ip.outputs.ip }}
      # Sign your ACR OCI artifact using private key stored in AKV
      - name: sign ACR artifact using key pair from AKV
        uses: notaryproject/notation-action/sign@b6fee73110795d6793253c673bd723f12bcf9bbb # v1.2.2
        with:
          plugin_name: azure-kv
          plugin_url: https://github.com/Azure/notation-azure-kv/releases/download/v1.2.1/notation-azure-kv_1.2.1_linux_amd64.tar.gz
          plugin_checksum: 67c5ccaaf28dd44d2b6572684d84e344a02c2258af1d65ead3910b3156d3eaf5
          key_id: ${{ env.KEY_ID }}
          target_artifact_reference: ${{ env.target_artifact_reference }}
          signature_format: cose
          plugin_config: |-
            self_signed=true
          # If you are using self-signed certificate from AKV, then the `plugin_config` should be:
          # plugin_config: |-
          #   self_signed=true
          # ca_certs=.github/cert-bundle/cert-bundle.crt
          force_referrers_tag: "true"
      - name: Remove runner IP from Key Vault
        if: always()
        run: |
          az keyvault network-rule remove \
            --name computerbutler-keyvault \
            --resource-group computerbutler \
            --ip-address ${{ steps.ip.outputs.ip }}
      - name: Extract current Helm chart version
        id: chart
        run: |
          VERSION=$(grep '^version:' charts/caddy-ingress-controller/Chart.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Generate azureManifest.yaml
        run: |
          sed "s/__VERSION__/${{ steps.chart.outputs.version }}/g" \
            azureManifest.yaml.tpl > manifest.yaml
      - name: Build CNAB Bundle and Publish to ACR
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: mcr.microsoft.com/container-package-app:latest
          options: -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/data --entrypoint "/bin/bash"
          run: |
              cd /data
              cpa buildbundle
